# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on: [push, pull_request]

name: Quickstart

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install NuShell
        uses: hustcer/setup-nu@c6d9051e49681bbb7df7eddd473c04d8bbcef9e1

      - name: Install Just
        uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6

      - uses: taiki-e/install-action@d12e869b89167df346dd0ff65da342d1fb1202fb
        with:
          tool: nextest
      - name: Run tests (nextest)
        run: just test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install stable toolchain
        # Pin based on current `rust-version` in Cargo.toml.
        # IMPORTANT: Upgrade `dtolnay/rust-toolchain@*` version when `rust-version` changes.
        uses: dtolnay/rust-toolchain@1.88
        with:
          components: rustfmt, clippy

      - name: Install Just
        uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6

      - name: Run just lint
        run: just lint
