# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on: [push, pull_request]

name: Quickstart

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install NuShell
        uses: hustcer/setup-nu@v3
        env:
          GITHUB_TOKEN: ${{ secrets.STELAE_GITHUB_TOKEN }}

      - name: Install Just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.STELAE_GITHUB_TOKEN }}

      - uses: taiki-e/install-action@v1
        with:
          tool: nextest
      - name: Run tests (nextest)
        run: just nextest

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@1.77 # Pin based on current `rust-version` in Cargo.toml. IMPORTANT: Upgrade version when `rust-version` changes.
        with:
          components: rustfmt, clippy

      - name: Install Just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.STELAE_GITHUB_TOKEN }}

      - name: Run just lint
        run: just lint
