//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "commit")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub sha: String,
    pub date: Date,
    pub revoked: bool,
    pub publication_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::change_commit::Entity")]
    ChangeCommit,
    #[sea_orm(
        belongs_to = "super::publication::Entity",
        from = "Column::PublicationId",
        to = "super::publication::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Publication,
}

impl Related<super::change_commit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChangeCommit.def()
    }
}

impl Related<super::publication::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Publication.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
